version: "3.9"
services:

  # Fix Ownership of Build Directory
  # Thanks to Bug in Docker itself
  # We need to use steps like this
  # Because by default, the volume directory
  # Is owned by Root
  # So this helps correct it
  change-vol-ownership:
    # We can use any image we want as long as we can chown
    image: private/zmk
    # Need a user priviliged enough to chown
    # env_file: env.list
    user: "root"
    # Specify the group in question
    group_add:
      - '1000'
    volumes:
      # The volumes to chown
      - /tank/anbaar/projects/hobbies/zmk_firmwares/zmk:/workspace/zmk
      - /tank/anbaar/projects/hobbies/zmk_firmwares/zmk-config-totem:/workspace/zmk-config
      - /tmp:/tmp
      - zmk_root_user:/root
      - zmk_zephyr:/workspace/zmk/zephyr
      - zmk_zephyr_modules:/workspace/zmk/modules
      - zmk_zephyr_tools:/workspace/zmk/tools
    command:
      - bash
      - -c
      - |
        mkdir -p "/workspace/zmk-config/output"
        chown -R 1000:1000 /workspace/zmk /workspace/zmk/zephyr /workspace/zmk/modules /workspace/zmk/tools /root /tmp "/workspace/zmk-config/output"

  build:
    user: "1000:1000"
    image: private/zmk
    working_dir: /workspace/zmk/app
    # env_file: env.list
    command:
      - bash
      - -c
      - |
        ls
    volumes:
      # The volumes to chown
      - /tank/anbaar/projects/hobbies/zmk_firmwares/zmk:/workspace/zmk
      - /tank/anbaar/projects/hobbies/zmk_firmwares/zmk-config-totem:/workspace/zmk-config
      - /tmp:/tmp
      - zmk_root_user:/root
      - zmk_zephyr:/workspace/zmk/zephyr
      - zmk_zephyr_modules:/workspace/zmk/modules
      - zmk_zephyr_tools:/workspace/zmk/tools

    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully

volumes:
  zmk_root_user:
    name: zmk-root-user-3.2.0
  zmk_zephyr:
    name: zmk-zephyr-3.2.0
  zmk_zephyr_modules:
    name: zmk-zephyr-modules-3.2.0
  zmk_zephyr_tools:
    name: zmk-zephyr-tools-3.2.0
