# version: "3.9"
services:

  # Fix Ownership of Build Directory
  # Thanks to Bug in Docker itself
  # We need to use steps like this
  # Because by default, the volume directory
  # Is owned by Root
  # So this helps correct it
  change-vol-ownership:
    # We can use any image we want as long as we can chown
    image: private/zmk
    secrets:
      - source: khersak_ssh_key
    # Need a user priviliged enough to chown
    # env_file: env.list
    user: "root"
    # Specify the group in question
    group_add:
      - '1000'
    volumes:
      # The volumes to chown
      # - /tank/anbaar/projects/hobbies/zmk_firmwares/zmk:/workspace/zmk
      - ${HOST_CONFIG_DIR}:${DOCKER_CONFIG_DIR}
      - /tmp:/tmp
      - my_zmk:${DOCKER_ZMK_DIR}
      - zmk_root_user:/root
      - zmk_zephyr:${DOCKER_ZMK_DIR}/zephyr
      - zmk_zephyr_modules:${DOCKER_ZMK_DIR}/modules
      - zmk_zephyr_tools:${DOCKER_ZMK_DIR}/tools
    command:
      - bash
      - -c
      - |
        mkdir -p "/workspace/zmk-config/output"
        chown -R 1000:1000 /workspace/zmk /workspace/zmk/zephyr /workspace/zmk/modules /workspace/zmk/tools /root /tmp /workspace/zmk-config/output || echo

  build:
    user: "1000:1000"
    image: private/zmk
    environment:
      - ZEPHYR_VERSION=${ZEPHYR_VERSION}
      - zephyr_version=${ZEPHYR_VERSION}
    secrets:
      - khersak_ssh_key
        # target: /home/hamid/.ssh/id_ed25519
        # uid: ${USER_ID}
        # gid: ${GROUP_ID}
        # mode: 400
    working_dir: /workspace/zmk
    # env_file: env.list
    command:
      - bash
      - -c
      - |
        ls
    volumes:
      # The volumes to chown
      # - /tank/anbaar/projects/hobbies/zmk_firmwares/zmk:/workspace/zmk
      - ${HOST_CONFIG_DIR}:${DOCKER_CONFIG_DIR}
      - /tmp:/tmp
      - my_zmk:${DOCKER_ZMK_DIR}
      - zmk_root_user:/root
      - zmk_zephyr:${DOCKER_ZMK_DIR}/zephyr
      - zmk_zephyr_modules:${DOCKER_ZMK_DIR}/modules
      - zmk_zephyr_tools:${DOCKER_ZMK_DIR}/tools
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully

secrets:
  khersak_ssh_key:
    file: ${HOST_CONFIG_DIR}/.khersak_id_rsa

volumes:
  zmk_root_user:
    name: zmk-root-user-3.5.0
  zmk_zephyr:
    name: zmk-zephyr-3.5.0
  zmk_zephyr_modules:
    name: zmk-zephyr-modules-3.5.0
  zmk_zephyr_tools:
    name: zmk-zephyr-tools-3.5.0
  my_zmk:
    name: my_zmk
    external: true
